### ISSUE TITLE
Error compiling fragment shader

### ISSUE THREAD

**Issue by shovon** [wwwtyro/vixel#1]
Hi there.

I've recently given vixel a try. I was eager to see the results, but only to be faced with errors arising from fragment shaders failing to compile.

Is this something that I'm doing wrong, or is this actually a problem with how the shaders were written?

```
file number 0: webpack:///./node_modules/regl-atmosphere-envmap/index.js?:11:25
   1|  
   2|        precision highp float;
   3|  
   4|        uniform vec3 sundir;
   5|  
   6|        varying vec3 pos;
   7|  
   8|        #pragma glslify: atmosphere = require(glsl-atmosphere)
   9|  
  10|        void main() {
  11|          vec3 color = atmosphere(
    |                      ^^^
    | no matching overloaded function found
    | ^^^
    | dimension mismatch
    |                    ^^^
    | cannot convert from 'const mediump float' to 'highp 3-component vector of float'
    | 
  12|            normalize(pos),
  13|            vec3(0,6372e3,0),
  14|            normalize(sundir),
  15|            22.0,
  16|            6371e3,
  17|            6471e3,
  18|            vec3(5.5e-6, 13.0e-6, 22.4e-6),
  19|            21e-6,
  20|            8e3,
  21|            1.2e3,
  22|            0.758
  23|          );
  24|  
  25|          gl_FragColor = vec4(color, 1);
  26|        }
  27|      

regl.js:322 file number unknown: webpack:///./node_modules/regl-atmosphere-envmap/index.js?:11:25
   0|  
    | ^^^
    | WARNING: 0:8: 'glslify' : unrecognized pragma
    | 
```

**Comment by wwwtyro** [comment]
Sorry about the trouble. Couple of questions: have you tried v1.0.1 of vixel, and are you using browserify?

**Comment by wwwtyro** [comment]
Ah, I see you're using webpack. I haven't played with using browserify transforms with webpack. There's this thing - though I'm not sure if it's something I need to do or you: https://github.com/webpack-contrib/transform-loader. I'll try to dig into it soon.

**Comment by shovon** [comment]
Hey, thanks for the prompt response. Indeed I am using webpack. I will give browserify a try.

p.s. Awesome work! I'm really liking what you're doing.

**Comment by wwwtyro** [comment]
Thanks! Let me know how it goes :)

**Comment by shovon** [comment]
This works great with browserify! Thanks!

**Comment by wwwtyro** [comment]
\o/

**Comment by jtenner** [comment]
Yeah I hit the same problem.

In my `index.ts` I used the `transform-loader` like this.

```ts
const Vixel = require("!transform-loader?glslify!vixel");
```

When I try this, it results in a `TypeError: stream.on is not a function`

```
C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\transform-loader\index.js:30
                stream.on("data", function(b) {
                       ^

TypeError: stream.on is not a function
    at next (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\transform-loader\index.js:30:10)
    at C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\transform-loader\index.js:23:4
    at doResolve (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\enhanced-resolve\lib\Resolver.js:160:12)
    at hook.callAsync (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\enhanced-resolve\lib\Resolver.js:237:23)
    at _fn0 (eval at create (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:36:23)
    at hook.callAsync (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\enhanced-resolve\lib\Resolver.js:237:23)
    at _fn0 (eval at create (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at hook.callAsync (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\enhanced-resolve\lib\Resolver.js:237:23)
    at _fn0 (eval at create (C:\Users\jtenner\Desktop\projects\vixel-test\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
```

I would be happy to help with this problem, but it might just be that `glslify` is not compatible with `transform-loader`.

Instead we could try using the `glslifyloader` located here: https://github.com/glslify/glslify-loader

Any advice on how to get this to work?

**Comment by shovon** [comment]
I'm guessing that you're using Webpack?

I think regl does not play well with Webpack.

**Comment by jtenner** [comment]
https://www.giacomodebidda.com/how-to-get-started-with-regl-and-webpack/

I know that this was an article I saw two years ago.
